### ISSUE TITLE
Share Goals/Progress to facebook

### ISSUE THREAD

**Issue by BowersMatthew** [vcu-cmsc355-f17/android-app-the-neverending-tree#4]
## As an Extrovert, so that I can feel validated in my life objectives, I want to be able to add goals via my social media(facebook) account
- [x] Scenario 1:
	- Given that I have a facebook/google/social media account
	- When I go to the login/register view
	- Then I should be able to login with my facebook account
- [x] Scenario 2:
	- Given that I have logged in via social media
	- When I go to my goals list
	- Then I should be able see some information associated with my facebook account, such as my name
- [x] Scenario 3
	- Given that I am logged in via social media
	- When I logout of my social media account
	- Then I should no longer be able to see my goals list

**Comment by whiskeyromeo** [comment]
Just needs testing
