### ISSUE TITLE
earn points for meeting goals

### ISSUE THREAD

**Issue by whiskeyromeo** [vcu-cmsc355-f17/android-app-the-neverending-tree#5]
- [ ] As a procrastinator, so that I can ensure that I am making progress, I want to be rewarded for meeting my goals.
	- [x] Scenario 1:
		- Given that I have created a goal
		- When I have been gotten a prompt asking if I have met that goal
		- Then if I click yes I should gain points for meeting that goal.
	- [x] Scenario 2:
		- Given that I have gotten points for meeting a goal repeatedly
		- When I have gotten a certain amount of points
		- Then I should earn a badge
	- [ ] Scenario 3:
		- Given that I have earned points and badges for meeting goals
		- When I am on the "User Goals" screen
		- Then I should be able to see the points I have earned

**Comment by DoraEx** [comment]
I've been looking at how everything will go together for first iteration, and adding/recording time to a goal seems to be the first stepping stone that we need before calculating points. I am going to remove this and and add task completion issue.

**Comment by BowersMatthew** [comment]
Excellent.
