### ISSUE TITLE
View goal detail/progress

### ISSUE THREAD

**Issue by BowersMatthew** [vcu-cmsc355-f17/android-app-the-neverending-tree#7]
## As a user, I want to be able to view my progress on my goals so that I can see how much time I've spent on goals.
- [x] Scenario 1:
	- Given that I go to the "main screen"
	- When I arrive on the main goals page
	- Then I see a list of active goals
- [x] Scenario 2: 
	- Given that I am on the main screen
	- When I click on an active goal
	- Then I go to the goal detail page
- [x] Scenario 3: 
	- Given that I am on the details page
	- When I click the back button
	- Then I will go back to the main page to see all goals.

**Comment by whiskeyromeo** [comment]
Tests for this should be found [In the UserGoalsActivityTest file](https://github.com/vcu-cmsc355-f17/android-app-the-neverending-tree/blob/master/app/src/androidTest/java/com/github/neverendingtree/neverendingtasks/activities/UserGoalsActivityTest.java)
