### ISSUE TITLE
Login/Register for App

### ISSUE THREAD

**Issue by whiskeyromeo** [vcu-cmsc355-f17/android-app-the-neverending-tree#8]
## A user should be able to sign into the app
- [x] Scenario 1:
	- Given that I am a registered user
	- When I enter correct login information
	- The I should be on my landing page
- [x] Scenario 2:
	- Given that I am a registerd user
	- When I correctly enter my username but mistype my password
	- Then I should be asked to try agin
- [x] Scenario 3: 
	- Given that I am not yet registed
	- When I click register
	- Then I will be taken to the registration page
- [x] Finish testing

**Comment by BowersMatthew** [comment]
Done Except 1 test only passes on every other attempt.

**Comment by whiskeyromeo** [comment]
Tests for this are found [in the LoginActivityTest file](https://github.com/vcu-cmsc355-f17/android-app-the-neverending-tree/blob/master/app/src/androidTest/java/com/github/neverendingtree/neverendingtasks/activities/LoginActivityTest.java)
